build:
  image: sedouard/node-mongo:latest
  commands:
deploy:
  git_push:
    branch: master
    remote: dokku@vmpower.centralus.cloudapp.azure.com:ember-notification-hub
    force: true
    when:
      branch: master
