build:
  image: sedouard/node-mongo:latest
  commands:
    - npm set registry http://10.0.0.5:4873/
    - npm install
    - npm install ember-cli -g
    - ember test
deploy:
  git_push:
    branch: master
    remote: dokku@vmpower.centralus.cloudapp.azure.com:ember-notification-hub
    force: true
    when:
      branch: master
